project:
  type: website
  title: "Handling and Sharing Qualitative Data Responsibly and Effectively"

website:
  page-navigation: true
  search: 
    location: navbar
  navbar:
    tools:
     - text: About RDS
       href: 00_about.qmd
     - icon: github
       href: https://github.com/rcurty/qualdata-training
       menu:
       - text: Source Code
         url: https://github.com/rcurty/qualdata-training
         target: _blank
       - text: Report a Bug
         url: https://github.com/rcurty/qualdata-training/issues
         target: _blank
    
        
  sidebar:
    style: "docked"
    border: true
    collapse-level: 1
    contents:
    - href: index.qmd
      text: "Home"
    - section: "Planning & Collecting"
      contents: 
        - text: Qualitative Data
          href: 01_qual-data.qmd
        - text: Data Management Planning
          href: 02_dmp.qmd
        - text: Ethical Considerations for HS Research
          href: 03_ethics.qmd
        - text: Interview Data
          href: 04_data-interviews.qmd
        - text: Running Example
          href: 05_example.qmd
    - section: "Analyzing & Documenting"
      contents:     
        - text: Data De-identification
          href: 06_deidentification.qmd
        - text: Coding Analysis
          href: 07_analysis.qmd
        - text: Computer-Aided Analysis Tools
          href: 08_tools.qmd
        - text: QualCoder
          href: 09_qualcoder.qmd
        - text: Coding & Documenting with QualCoder 
          href: 10_qualcoder-coding.qmd
    - section: "Sharing & Archiving"
      contents:      
         - text: What and Where to Share?
           href: 11_sharing.qmd
    - section: "Reusing"
      contents:    
         - text: QHS Data Secondary Analysis
           href: 12_reusing.qmd
  page-footer:
    background: blue
    center: This website is built with [Quarto](https://quarto.org/), [RStudio/Posit](https://posit.co/),
      and [webexercises R package](https://cran.r-project.org/web/packages/webexercises/index.html).
      UCSB Library Research Data Services. [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en)
    left: |
      <img src="images/RDS-logo.png" alt="UCSB Library Research Data Services logo" width="250"/>
format:
  html:
    theme: adapt-meds-website-styles.scss
    toc: false
    page-layout: full
    code-line-numbers: true
    filters:
      - naquiz


